# Generated by Django 2.1.5 on 2019-11-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_auto_20191029_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='extra_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
