# Generated by Django 2.2.6 on 2019-11-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_auto_20191029_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='extra_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
